---
title: "20. Introduction to Coordinate Reference Systems"
author: "Lucy Block"
format:
  html:
    code-copy: true
    toc-location: right
editor: visual
link-external-newwindow: true
link-external-icon: true
---

## Video Tutorial

{{< video https://youtu.be/3N3MjZQbCaw?feature=shared >}}

#### In this tutorial

Understand the basics of Coordinate Reference Systems (CRSs) and map projections. See how they function based on the layers you add and learn to adjust your project CRS.

Learn more about troubleshooting CRS issues: [I Hate Coordinate Systems!](https://ihatecoordinatesystems.com/){target="_blank"}

**Timestamps (Click a link to start that segment in a new window)**

[0:00 - 5:25](https://youtu.be/3N3MjZQbCaw?si=kA8Pfp4KwkXNTgfc): Define a project CRS by first loading the borough boundaries shapefile, which is defined in the NYC-appropriate CRS 2263.

[5:22 - 8:34](https://youtu.be/3N3MjZQbCaw?si=QT8DQ_7eMdZtEyD_&t=322): Load a shapefile first containing stormwater outflow features across all of NYS in with a CRS of 4326, which looks distorted for NYC. Change the whole project CRS to 2263 to get NYC back to a familiar shape.

## Data downloads

[Borough boundaries](https://data.cityofnewyork.us/City-Government/Borough-Boundaries/gthc-hcne)

[NYC subway stations](https://drive.google.com/file/d/13kz4Ud11KQSGTi3H2PVC7Uw3sxsAch-6/view) (Saved copy)

Stormwater outfalls:

-   via [NYS GIS Clearinghouse](https://data.gis.ny.gov/datasets/94a7b7a3c5cc4f409622523b04ee06bf_0/explore?location=42.242572%2C-75.466961%2C7.24) - download GeoJSON format for clearest difference in CRS

-   [Saved copy](https://drive.google.com/open?id=10z5v3ZQ2LrKg363FYahnwTfxUBZzOXZ1&usp=drive_fs)
