---
title: "29. Selecting features"
author: "Lucy Block"
format:
  html:
    code-copy: true
    toc-location: right
editor: visual
link-external-newwindow: true
link-external-icon: true
---

## Video Tutorial

{{< video https://www.youtube.com/watch?v=okgmaghP5Uc >}}

## In this tutorial

Select features manually with the attribute table or directly on your map, as well as select features by value and with mathematical functions

**Timestamps (Click a link to start that segment in a new window)**

[0:00-1:26](https://www.youtube.com/watch?v=okgmaghP5Uc): Open the Attribute Table to browse the [borough boundaries](https://data.cityofnewyork.us/City-Government/Borough-Boundaries/gthc-hcne) shapefile. Manually select row(s) in the Attribute Table and view them in yellow in the main map extent. Click the "Deselect all features from the layer" button (yellow square with a cancel symbol) to deselect everything.

[1:26-2:35](https://youtu.be/okgmaghP5Uc?si=ti8XKAcYb38CyQ88&t=87):

-   Click the dropdown arrow of the "Select Features by Area or Single Click" button (gray square, smaller yellow square, and cursor).

-   Click "Select Feature(s)" and draw a rectangle to select the features you want.

-   Use "Select Features by Polygon" to draw a custom selection by clicking points on your map that encompass the features you want to select, then right clicking to close the selection polygon.

-   If you hold the shift button, you can add features to your selection or remove them by clicking features that have already been selected.

[2:35-4:31](https://youtu.be/okgmaghP5Uc?si=D-svZnE-tdabRWFt):

-   Click "Select Features by Value" button (gray square with white rows in front of a yellow square). Type Bronx in the BoroName field and click "Select Features." Type 3 in BoroCode and click Select Features to select Brooklyn.

-   To add to your selection instead of replacing the current selection, use the dropdown arrow next to Select Features and choose "Add to Current Selection." Deselect all features.

-   Click the button that shows "Exclude Field" to the right of the BoroCode field and select "Greater than (\>)." Type 1 in the BoroCode field.

-   Click the "Invert Selection" button (one yellow triangle and one gray triangle) to swap which features are selected.

[4:31-5:22](https://youtu.be/okgmaghP5Uc?si=UXmV0k0V7AymcdKQ&t=271): When you have the selection that you want, right click your layer, click Export, then "Save Selected Features As." Select or keep ESRI Shapefile as the format, (**important!**) select the three dots to the right of the File name field to save the new shapefile to your project folder, and make sure "Save only selected features" is clicked. Click OK.

## Data downloads 

[Borough boundaries](https://data.cityofnewyork.us/City-Government/Borough-Boundaries/gthc-hcne)
