project: 
  type: website
  output-dir: docs
  
website:
  title: "URPL 1620 Tutorials"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Learning R"
        contents:
          - 1.installing_r.qmd
          - 2.r_projects.qmd
          - 3.packages_functions.qmd
          - 4.readingdata_datatypes.qmd
          - 5.datacleaning_pipe.qmd
          - 6.select_filter.qmd
          - 7.mutate.qmd
          - 8.groupby_summarize.qmd
          - 9.arrange_writecsv.qmd
          - 10.joins.qmd
          - 11.pivoting.qmd
          - 12.ggplot.qmd
          - 13.stringr.qmd
          - 14.lubridate.qmd
          - 15.apis.qmd
          - 16.tidycensus.qmd
          - 17.sf.qmd
      - section: "QGIS"
        contents: 
          - 18.qgis_setup.qmd
          - 19.adding_spatial_layers.qmd
          - 20.intro_crs.qmd
          - 21.geocoding.qmd
          - 22.spatial_csv.qmd
          - 23.tabular_joins.qmd
          - 24.calculate_field.qmd
          - 25.choropleth.qmd
          - 26.basemaps_points.qmd
          - 27.print_layout_export.qmd
          - 28.symbols_by_size.qmd
          - 29.select.qmd
          - 30.geoprocessing.qmd
          - 31.join_by_location.qmd
          - 32.points_in_polygon.qmd
          - 33.labeling.qmd
          - 34.isochrones_areas.qmd
          - 35.inset_maps.qmd
          - 36.heatmaps.qmd
          - 37.dot_density.qmd