project: 
  type: website
  
website:
  title: "Learning R"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Basics"
        contents:
          - installing_r.qmd