project: 
  type: website
  output-dir: docs
  
website:
  title: "URPL 1620 Tutorials"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Getting Started with R"
        contents:
          - 1.installing_r.qmd
          - 2.r_projects.qmd
          - 3.packages_functions.qmd
          - 4.readingdata_datatypes.qmd
      - section: "R Basics"
        contents:
          - 5.datacleaning_pipe.qmd
          - 6.select_filter.qmd
          - 7.mutate.qmd
          - 8.groupby_summarize.qmd
          - 9.arrange_writecsv.qmd
      - section: "R Intermediates"
        contents:
          - 10.joins.qmd
          - 11.pivoting.qmd
          - 12.ggplot.qmd
          - 13.stringr.qmd
          - 14.lubridate.qmd
      - section: "R Advanced"
        contents:
          - 15.apis.qmd
          - 16.tidycensus.qmd
          - 17.sf.qmd
      - section: "QGIS Basics"
        contents: 
          - 18.qgis_setup.qmd