project: 
  type: website
  output-dir: docs
  
website:
  title: "Learning R"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Basics"
        contents:
          - 1.installing_r.qmd
          - 2.r_projects.qmd
          - 3.packages_functions.qmd
          - 4.readingdata_datatypes.qmd