project: 
  type: website
  output-dir: docs
  
website:
  title: "Learning R"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Getting Started"
        contents:
          - 1.installing_r.qmd
          - 2.r_projects.qmd
          - 3.packages_functions.qmd
          - 4.readingdata_datatypes.qmd
      - section: "Basics"
        contents:
          - 5.datacleaning_pipe.qmd
          - 6.select_filter.qmd
          - 7.mutate.qmd
          - 8.groupby_summarize.qmd
          - 9.arrange_writecsv.qmd
      - section: "Intermediates"
        contents:
          - 10.stringr.qmd
          - 11.lubridate.qmd
          - 12.joins.qmd
          - 13.pivoting.qmd
          - 14.ggplot.qmd
      - section: "Advanced"
        contents: